databases:
  - name: brainstaq_app_development
    ipAllowList: []
    databaseName: brainstaq_app_development
    user: sircliffjoe

services:
  - type: web
    name: brainstaq
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: brainstaq_app_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
