development:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - high
  - default
  - mailers
  - process_web_hook
  - brainstaq_app_development_default
  - brainstaq_app_production_default
  - brainstaq_app_production_ahoy
  - brainstaq_app_production_mailers