height: 300
menubar: true
branding: false
file_picker_types: 'file image media'
file_picker_callback: true

automatic_uploads: true
image_title: true
toolbar:
  - undo redo | table | formatselect | code | bold italic backcolor | image |link alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat
plugins:
  - image
  - link
  - media
  - print
  - preview
  - lists
  - textcolor
  - colorpicker
